/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import clases.Cafetera;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {
Cafetera c;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAc = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtTaz = new javax.swing.JTextField();
        txtAg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdEn = new javax.swing.JButton();
        cmdLlen = new javax.swing.JButton();
        cmdVac = new javax.swing.JButton();
        cmdSer = new javax.swing.JButton();
        cmdAgr = new javax.swing.JButton();
        cmdApa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Máxima");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtMax.setEditable(false);
        jPanel5.add(txtMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, -1));

        jLabel2.setText("Actual");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txtAc.setEditable(false);
        jPanel5.add(txtAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 60, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 110));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(txtTaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 40, 50, -1));

        txtAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgActionPerformed(evt);
            }
        });
        jPanel6.add(txtAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 60, -1));

        jLabel3.setText("Cantidad");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setText("Agregar");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 180, 120));

        cmdEn.setText("Encender");
        cmdEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnActionPerformed(evt);
            }
        });
        getContentPane().add(cmdEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        cmdLlen.setText("Llenar");
        cmdLlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenActionPerformed(evt);
            }
        });
        getContentPane().add(cmdLlen, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 190, 70, -1));

        cmdVac.setText("Vaciar");
        cmdVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVacActionPerformed(evt);
            }
        });
        getContentPane().add(cmdVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 80, -1));

        cmdSer.setText("Servir");
        cmdSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSerActionPerformed(evt);
            }
        });
        getContentPane().add(cmdSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 80, -1));

        cmdAgr.setText("Agregar");
        cmdAgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgrActionPerformed(evt);
            }
        });
        getContentPane().add(cmdAgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        cmdApa.setText("Apagar");
        cmdApa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdApaActionPerformed(evt);
            }
        });
        getContentPane().add(cmdApa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgActionPerformed

    private void cmdEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnActionPerformed
        c = new Cafetera();

        txtMax.setText("" + c.getMaxima());
        txtAc.setText("" + c.getActual());
    }//GEN-LAST:event_cmdEnActionPerformed

    private void cmdLlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenActionPerformed
      int llenar;
        llenar = c.getActual();
        c.Llenar(llenar);
        txtAc.setText("" + c.getActual());
        txtTaz.setText("");
        txtAg.setText("");        
    }//GEN-LAST:event_cmdLlenActionPerformed

    private void cmdVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVacActionPerformed
      int vaciar = 0;
        txtAc.setText("" + c.Vaciar());       
    }//GEN-LAST:event_cmdVacActionPerformed

    private void cmdSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSerActionPerformed
        int t;
            t = Integer.parseInt(txtTaz.getText());
            c.Servir(t);
            txtAc.setText("" + c.getActual());
            txtTaz.setText("");
    }//GEN-LAST:event_cmdSerActionPerformed

    private void cmdAgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgrActionPerformed
        int ag;
        ag = Integer.parseInt(txtAg.getText());
                c.AgregarCafe(ag);
                txtAc.setText("" + c.getActual());
                txtAg.setText("");
            
        
    }//GEN-LAST:event_cmdAgrActionPerformed

    private void cmdApaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdApaActionPerformed
        txtAc.setText("");
        txtAg.setText("");
        txtMax.setText("");
        txtTaz.setText("");
        
    }//GEN-LAST:event_cmdApaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgr;
    private javax.swing.JButton cmdApa;
    private javax.swing.JButton cmdEn;
    private javax.swing.JButton cmdLlen;
    private javax.swing.JButton cmdSer;
    private javax.swing.JButton cmdVac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtAc;
    private javax.swing.JTextField txtAg;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtTaz;
    // End of variables declaration//GEN-END:variables
}
