/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import ejercicios.Fraccionario;
import ejercicios.Helper;
import ejercicios.DenominadorCeroException;

/**
 *
 * @author Usuario
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNum1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDen1 = new javax.swing.JTextField();
        cmbOp = new javax.swing.JComboBox<>();
        txtNum2 = new javax.swing.JTextField();
        txtDen2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtNum3 = new javax.swing.JTextField();
        txtDen3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        cmdOp = new javax.swing.JButton();
        cmdReset = new javax.swing.JButton();
        txtMixto = new javax.swing.JTextField();
        cmdConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Fraccionarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, 40));
        jPanel1.add(txtDen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, -1));

        cmbOp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sumar", "Restar", "Multiplicar", "dividir", " " }));
        cmbOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOpActionPerformed(evt);
            }
        });
        jPanel1.add(cmbOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));
        jPanel1.add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 60, -1));
        jPanel1.add(txtDen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 60, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 60, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        txtNum3.setEditable(false);
        jPanel1.add(txtNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 60, -1));

        txtDen3.setEditable(false);
        txtDen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDen3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtDen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 60, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 60, 10));

        cmdOp.setText("Operate");
        cmdOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOpActionPerformed(evt);
            }
        });
        jPanel1.add(cmdOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        cmdReset.setText("Reset");
        cmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetActionPerformed(evt);
            }
        });
        jPanel1.add(cmdReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 70, -1));

        txtMixto.setEditable(false);
        jPanel1.add(txtMixto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 50, -1));

        cmdConvertir.setText("Convertir");
        cmdConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConvertirActionPerformed(evt);
            }
        });
        jPanel1.add(cmdConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOpActionPerformed
        int op,n1,n2,n3,d1,d2,d3;
        Fraccionario f1,f2,f3=null;
        txtMixto.setText("");
        op= cmbOp.getSelectedIndex();
        n1=Integer.parseInt(txtNum1.getText());
        n2=Integer.parseInt(txtNum2.getText());
        d1=Integer.parseInt(txtDen1.getText());
        d2=Integer.parseInt(txtDen2.getText());
        try{
            f1= new Fraccionario(n1,d1);
            f2= new Fraccionario(n2,d2);
            switch(op){
                case 0:
                    f3=f1.suma(f2);
                    break;
                case 1:
                    f3=f1.resta(f2);
                    break;
                case 2:
                    f3=f1.multiplicacion(f2);
                    break;
                   
                case 3:
                    f3=f1.division(f2);
                    
            }
            txtNum3.setText(""+f3.getNumerador());
            txtDen3.setText(""+f3.getDenominador());
            
            
        }catch(DenominadorCeroException e){
            Helper.mensaje(null, "No puede digitar el número 0 en el Denominador", "Error", 2);
        }
        
        
    }//GEN-LAST:event_cmdOpActionPerformed

    private void cmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetActionPerformed
        txtNum1.setText("");
        txtNum2.setText("");
        txtNum3.setText("");
        txtDen1.setText("");
        txtDen2.setText("");
        txtDen3.setText("");
        txtNum1.requestFocusInWindow();
        cmbOp.setSelectedIndex(0);
    }//GEN-LAST:event_cmdResetActionPerformed

    private void cmbOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOpActionPerformed

    private void txtDen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDen3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDen3ActionPerformed

    private void cmdConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConvertirActionPerformed
       int op,mixto,n3,d3,cociente;
       n3=Integer.parseInt(txtNum3.getText());
       d3=Integer.parseInt(txtDen3.getText());
       op=n3%d3;
       cociente=n3/d3;
       txtNum3.setText(String.valueOf(op));
       txtDen3.setText(String.valueOf(d3));
       txtMixto.setText(String.valueOf(cociente));
       
    }//GEN-LAST:event_cmdConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOp;
    private javax.swing.JButton cmdConvertir;
    private javax.swing.JButton cmdOp;
    private javax.swing.JButton cmdReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtDen1;
    private javax.swing.JTextField txtDen2;
    private javax.swing.JTextField txtDen3;
    private javax.swing.JTextField txtMixto;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtNum3;
    // End of variables declaration//GEN-END:variables
}
